version: '3.8'

services:

  app:
    container_name: node-fullcycle
    build: ./app
    tty: true
    entrypoint: sh -c "npm install && npm start"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql-fullcycle
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx-fullcycle
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - app

volumes:
  mysql:
    driver: local
