version: '3.8'

services:

  node-app:
    container_name: node-fullcycle
    build: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app/volumes:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fullcycle-network

  mysql:
    container_name: mysql-fullcycle
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullcycle-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx-fullcycle
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - fullcycle-network

networks:
  fullcycle-network:
    driver: bridge

volumes:
  mysql-data:
